const CAREER_COURSE_MAPPING: { [key: string]: any[] } = {
  fullstack: [
    {
      title: "The Complete JavaScript Course 2024",
      provider: "Udemy",
      level: "Beginner",
      duration: "69 hours",
      rating: 4.7,
      price: "$14.99",
      url: "https://www.udemy.com/course/the-complete-javascript-course/",
      description: "Master JavaScript, DOM manipulation, and async programming",
    },
    {
      title: "React - The Complete Guide",
      provider: "Udemy",
      level: "Intermediate",
      duration: "48 hours",
      rating: 4.8,
      price: "$14.99",
      url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
      description: "Learn React with hooks, Redux, and modern patterns",
    },
    {
      title: "Node.js, Express, MongoDB & More",
      provider: "Udemy",
      level: "Intermediate",
      duration: "40 hours",
      rating: 4.7,
      price: "$14.99",
      url: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
      description: "Build backend applications with Node.js and Express",
    },
    {
      title: "Full Stack Web Development",
      provider: "Coursera",
      level: "Intermediate",
      duration: "6 months",
      rating: 4.7,
      price: "$39/month",
      url: "https://www.coursera.org/specializations/full-stack-web-development",
      description: "Learn frontend and backend web development",
    },
    {
      title: "The Advanced Web Developer Bootcamp",
      provider: "Udemy",
      level: "Advanced",
      duration: "52 hours",
      rating: 4.6,
      price: "$14.99",
      url: "https://www.udemy.com/course/the-advanced-web-developer-bootcamp/",
      description: "Master advanced web development techniques",
    },
    {
      title: "Web Development by University of Michigan",
      provider: "Coursera",
      level: "Beginner",
      duration: "7 months",
      rating: 4.8,
      price: "$39/month",
      url: "https://www.coursera.org/specializations/web-design",
      description: "Learn web development from university experts",
    },
  ],
  "data-analyst": [
    {
      title: "The Complete Hands-On Introduction to Apache Spark",
      provider: "Udemy",
      level: "Intermediate",
      duration: "11 hours",
      rating: 4.6,
      price: "$14.99",
      url: "https://www.udemy.com/course/apache-spark-course/",
      description: "Master Apache Spark for big data analytics",
    },
    {
      title: "SQL for Data Analysis",
      provider: "DataCamp",
      level: "Beginner",
      duration: "4 weeks",
      rating: 4.8,
      price: "$29/month",
      url: "https://www.datacamp.com/courses/sql-for-data-analysis",
      description: "Learn SQL for data analysis and querying",
    },
    {
      title: "Data Visualization with Tableau",
      provider: "Udemy",
      level: "Intermediate",
      duration: "13 hours",
      rating: 4.7,
      price: "$14.99",
      url: "https://www.udemy.com/course/tableau-training-for-data-visualization/",
      description: "Create powerful visualizations with Tableau",
    },
    {
      title: "Python for Data Analysis",
      provider: "DataCamp",
      level: "Beginner",
      duration: "5 weeks",
      rating: 4.9,
      price: "$29/month",
      url: "https://www.datacamp.com/courses/python-for-data-analysis",
      description: "Learn Python specifically for data analysis",
    },
    {
      title: "Statistics Fundamentals",
      provider: "Coursera",
      level: "Intermediate",
      duration: "6 weeks",
      rating: 4.7,
      price: "Free",
      url: "https://www.coursera.org/learn/statistics",
      description: "Master statistics for data analysis",
    },
  ],
  "machine-learning": [
    {
      title: "Machine Learning Specialization",
      provider: "Coursera",
      level: "Intermediate",
      duration: "3 months",
      rating: 4.9,
      price: "$39/month",
      url: "https://www.coursera.org/specializations/machine-learning-introduction",
      description: "Learn ML fundamentals with Andrew Ng",
    },
    {
      title: "Deep Learning Specialization",
      provider: "Coursera",
      level: "Advanced",
      duration: "4 months",
      rating: 4.8,
      price: "$39/month",
      url: "https://www.coursera.org/specializations/deep-learning",
      description: "Master neural networks and deep learning",
    },
    {
      title: "TensorFlow Developer Certificate",
      provider: "Coursera",
      level: "Intermediate",
      duration: "4 weeks",
      rating: 4.7,
      price: "$39/month",
      url: "https://www.coursera.org/professional-certificates/tensorflow-in-practice",
      description: "Learn TensorFlow for machine learning",
    },
    {
      title: "Machine Learning with Python",
      provider: "Udemy",
      level: "Intermediate",
      duration: "22 hours",
      rating: 4.7,
      price: "$14.99",
      url: "https://www.udemy.com/course/machine-learning-with-python/",
      description: "Comprehensive machine learning course",
    },
    {
      title: "AI Engineering Bootcamp",
      provider: "AI Academy",
      level: "Advanced",
      duration: "12 weeks",
      rating: 4.9,
      price: "$2000",
      url: "https://www.ai-academy.com/bootcamp",
      description: "Intensive bootcamp for AI engineers",
    },
  ],
  "ui-ux-designer": [
    {
      title: "UI/UX Design Specialization",
      provider: "Coursera",
      level: "Beginner",
      duration: "3 months",
      rating: 4.8,
      price: "$39/month",
      url: "https://www.coursera.org/specializations/user-experience-design",
      description: "Master UI/UX design principles and tools",
    },
    {
      title: "Figma for UI/UX Design",
      provider: "Udemy",
      level: "Beginner",
      duration: "12 hours",
      rating: 4.9,
      price: "$14.99",
      url: "https://www.udemy.com/course/figma-ui-ux-design/",
      description: "Learn Figma for modern UI/UX design",
    },
    {
      title: "Design Thinking Workshop",
      provider: "Skillshare",
      level: "Beginner",
      duration: "2 hours",
      rating: 4.8,
      price: "$32/month",
      url: "https://www.skillshare.com/classes/Design-Thinking",
      description: "Master design thinking methodology",
    },
    {
      title: "User Research and Testing",
      provider: "Interaction Design Foundation",
      level: "Intermediate",
      duration: "6 weeks",
      rating: 4.9,
      price: "Free",
      url: "https://www.interaction-design.org/courses/user-research",
      description: "Learn user research techniques",
    },
    {
      title: "Graphic Design Masterclass",
      provider: "Udemy",
      level: "Intermediate",
      duration: "40 hours",
      rating: 4.6,
      price: "$14.99",
      url: "https://www.udemy.com/course/graphic-design-masterclass/",
      description: "Advanced graphic design techniques",
    },
  ],
  "cloud-engineer": [
    {
      title: "AWS Certified Solutions Architect",
      provider: "Udemy",
      level: "Intermediate",
      duration: "28 hours",
      rating: 4.8,
      price: "$14.99",
      url: "https://www.udemy.com/course/aws-certified-solutions-architect-associate/",
      description: "Prepare for AWS certification",
    },
    {
      title: "Kubernetes for Developers",
      provider: "Coursera",
      level: "Intermediate",
      duration: "4 weeks",
      rating: 4.7,
      price: "$39/month",
      url: "https://www.coursera.org/learn/kubernetes-for-developers",
      description: "Master Kubernetes container orchestration",
    },
    {
      title: "Docker & Kubernetes Masterclass",
      provider: "Udemy",
      level: "Intermediate",
      duration: "14 hours",
      rating: 4.8,
      price: "$14.99",
      url: "https://www.udemy.com/course/docker-kubernetes-the-complete-guide/",
      description: "Learn Docker and Kubernetes",
    },
    {
      title: "Azure Fundamentals",
      provider: "Microsoft Learn",
      level: "Beginner",
      duration: "3 weeks",
      rating: 4.9,
      price: "Free",
      url: "https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/",
      description: "Get started with Microsoft Azure",
    },
    {
      title: "Linux and Network Administration",
      provider: "Udemy",
      level: "Intermediate",
      duration: "32 hours",
      rating: 4.7,
      price: "$14.99",
      url: "https://www.udemy.com/course/linux-network-administration/",
      description: "Master Linux and networking fundamentals",
    },
  ],
}

export async function POST(request: Request) {
  try {
    const { careerPath } = await request.json()

    const courses = CAREER_COURSE_MAPPING[careerPath] || CAREER_COURSE_MAPPING.fullstack

    return Response.json({ courses })
  } catch (error) {
    console.error("[v0] Career courses error:", error)
    return Response.json({ courses: [], error: "Failed to fetch career courses" }, { status: 500 })
  }
}
